#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int leak_canary_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int leak_canary_notification = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int leak_canary_toast_background = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int MyButton = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int @__leak_canary_action = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int @__leak_canary_display_leak_failure = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int @__leak_canary_display_leak_list = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int @__leak_canary_row_connector = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int @__leak_canary_row_more = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int @__leak_canary_row_text = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int @__leak_canary_row_time = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int leak_canary_max_stored_leaks = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int leak_canary_watch_delay_millis = 2131099649;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int leak_canary_display_leak = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int leak_canary_heap_dump_toast = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int leak_canary_leak_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int leak_canary_ref_row = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int leak_canary_ref_top_row = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040016
			public const int ApplicationName = 2130968598;
			
			// aapt resource value: 0x7f040015
			public const int Hello = 2130968597;
			
			// aapt resource value: 0x7f040000
			public const int leak_canary_analysis_failed = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int leak_canary_class_has_leaked = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int leak_canary_could_not_save_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int leak_canary_could_not_save_title = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int leak_canary_delete = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int leak_canary_delete_all = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int leak_canary_display_activity_label = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int leak_canary_excluded_row = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int leak_canary_failure_report = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int leak_canary_leak_excluded = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int leak_canary_leak_list_title = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int leak_canary_no_leak_text = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int leak_canary_no_leak_title = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int leak_canary_notification_message = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int leak_canary_permission_notification_text = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int leak_canary_permission_notification_title = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int leak_canary_share_heap_dump = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int leak_canary_share_leak = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int leak_canary_share_with = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int leak_canary_storage_permission_activity_label = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int leak_canary_toast_heap_dump = 2130968596;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int leak_canary_LeakCanary_Base = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int leak_canary_Theme_Transparent = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
